name: AutoPEP8

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install AutoPEP8
        run: |
          python -m pip install --upgrade pip
          pip install autopep8

      - name: Run AutoPEP8
        run: |
          autopep8 --in-place --aggressive --aggressive **/*.py
