name: Radon

on: [push, pull_request]

jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Radon
        run: |
          python -m pip install --upgrade pip
          pip install radon

      - name: Run Radon
        run: |
          radon cc . -nc  # Check code complexity
          radon mi . -nc  # Check maintainability index
