name: Test each push using pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Check the commit
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
    - name: Test pytest for hw2
      if: always()
      run: pytest ./hw2/
    - name: Run AutoPep8
      if: always()
      run: autopep8 --in-place --aggressive --aggressive ./hw2/
