name: Test each push using pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Check the commit
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade autopep8
        pip install pytest
        pip install radon
        pip install bandit

    - name: Test with pytest
      run: |
        pytest

    - name: Test pytest for hw2
      if: always()
      run: pytest ./hw2/

    - name: Run AutoPep8
      if: always()
      run: autopep8 --in-place --aggressive --aggressive ./hw2/

    - name: Run Radon
      if : always()
      run: radon mi hw2_debugging.py rand.py >> /logs/radon_log

    - name: Run Bandit
      if : always()
      run: bandit -r hw2_debugging.py rand.py >> /logs/bandit_log
    
    - name: Commit log files
      run: |
        git config --global user.name 'm11dedhia'
        git config --global user.email 'm11dedhia@users.noreply.github.com'
        git add .
        git commit -am "Automated log file commit"
        git push
