name: CI for HW2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest autopep8 radon bandit

      - name: Run pytest for HW2
        run: pytest ./hw2/

      - name: Run AutoPEP8
        run: autopep8 --in-place --aggressive --aggressive ./hw2/*.py

      - name: Run Radon
        run: |
          mkdir -p logs
          radon cc ./hw2/ > logs/radon_log.txt

      - name: Run Bandit
        run: |
          mkdir -p logs
          bandit -r ./hw2/ -f txt -o logs/bandit_log.txt || echo "No issues found" > logs/bandit_log.txt