name: CI for HW2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest autopep8 radon bandit

      - name: Run pytest for HW2
        id: pytest_check
        run: pytest ./hw2/

      - name: Run AutoPEP8
        id: autopep8_check
        run: |
          autopep8 --in-place --aggressive --aggressive ./hw2/*.py
        continue-on-error: false

      - name: Run Radon
        id: radon_check
        run: |
          mkdir -p logs
          radon cc ./hw2/ > logs/radon_log.txt
        continue-on-error: false

      - name: Run Bandit
        id: bandit_check
        run: |
          mkdir -p logs
          bandit -r ./hw2/ -f txt -o logs/bandit_log.txt || echo "No issues found" > logs/bandit_log.txt
        continue-on-error: false

  outputs:  # This section will define outputs for each step
    pytest_result: ${{ steps.pytest_check.outcome }}
    autopep8_result: ${{ steps.autopep8_check.outcome }}
    radon_result: ${{ steps.radon_check.outcome }}
    bandit_result: ${{ steps.bandit_check.outcome }}
